# Autogeneration
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=100MB

###### Logging configuration ######
logging.pattern.console=%d{dd-MM-YYYY HH:mm:ss.SSS} [%t] %-5level %logger{36}:%L - %msg%n
logging.level.com.slabfolio.api=debug

server.use-forward-headers=true
server.forward-headers-strategy=native
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

